baseURL = "https://chail.tech/"
defaultContentLanguage = "zh-cn"
title = "chail's Blog"

theme = "DoIt"

enableRobotsTXT = true
enableEmoji = true

# ignore some build errors
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]